name: Deploy

on:
  pull_request:
    types:
      - closed
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: sam build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name Authenticate-Lambda --capabilities CAPABILITY_IAM --region us-east-1 --resolve-s3
      - run: aws lambda update-function-configuration --function-name Authenticate-Lambda --environment "Variables={REDIS_CLUSTER=${{ secrets.REDIS_CLUSTER }}, REDIS_PORT=${{ secrets.REDIS_PORT }}, MONGO_CLUSTER=${{ secrets.MONGO_CLUSTER }}, MONGO_LOGIN=${{ secrets.MONGO_LOGIN }}, MONGO_PASSW=${{ secrets.MONGO_PASSW }}, MONGO_TLS=${{ secrets.MONGO_TLS }} }"